### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by mudahayee** [drupalwxt/wxt-project#10]
I used the following command to install drupal:
"composer create-project drupalwxt/wxt-project:8.x-dev [projectname]"

I received the following error:
"In BaseInstaller.php line 68:
 Package type "drupal-console-library" is not supported"

Any thoughts to resolve?

**Comment by thomascraig** [comment]
Need to remove "drupal/console": "1.0.1" from composer.json
can run : composer create-project drupalwxt/wxt-project:8.x-dev [projectname] --stability dev --no-interaction --no-install  this will output the files in your project folder and than just remove the console ref in composer.json

**Comment by mudahayee** [comment]
This worked.  Thank you.
