### ISSUE TITLE
An issue with Entity Definition

### ISSUE THREAD

**Issue by mudahayee** [drupalwxt/wxt-project#11]
Hi, I am trying to install drupal. During the "Configuration Site" section, I get the following error:

`User deprecated function: EntityDefinitionUpdateManagerInterface::applyUpdates() is deprecated in 8.7.0 and will be removed before Drupal 9.0.0. Use \Drupal\Core\Entity\EntityDefinitionUpdateManagerInterface::getChangeList() and execute each entity type and field storage update manually instead. See https://www.drupal.org/node/3034742. in Drupal\Core\Entity\EntityDefinitionUpdateManager->applyUpdates() (line 175 of core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php).
Drupal\Core\Entity\EntityDefinitionUpdateManager->applyUpdates() (Line: 31)
_wxt_setup_base_configurations() (Line: 21)
wxt_install()
call_user_func_array('wxt_install', Array) (Line: 392)
Drupal\Core\Extension\ModuleHandler->invoke('wxt', 'install') (Line: 303)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1665)
install_install_profile(Array) (Line: 708)
install_run_task(Array, Array) (Line: 583)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 44)`

I am using the latest Durpal core 8.7.5 and I have tried following the instructions found here: https://www.drupal.org/node/3034742

But am unsuccessful.

Anyone know how to resolve this issue?

Thanks,
Muda

**Comment by sylus** [comment]
Ah thank you for this, our CI and everytime I install it is done in drush which bypasses this issue.

I'll commit a fix shortly but for now you can comment out this line as is logic I don't think is required anymore as Drupal's handling of fields is much improved:

```sh
/**
 * Setup base site configurations.
 */
function _wxt_setup_base_configurations() {
  // Ensure the translation fields are created in the database.
  // \Drupal::service('entity.definition_update_manager')->applyUpdates();
}
```

**Comment by sylus** [comment]
@zachomedia 

Will still need to test doesn't cause issues with translations field not being present yet as will need them for the language handling afterwards.

**Comment by mudahayee** [comment]
Thanks for the information.

So just to confirm, the file that needs to be changed is: "wxt.install"?
Will I need to reinstall? (ie. drop DB, recreate DB and reconfigure drupal?)

or applying a patch would be a better solution?

**Comment by sylus** [comment]
Yeah it would be that file (can see https://github.com/drupalwxt/wxt/commit/f5ff7022cc95cc6b7cf1397a779ff2798268cfb7).

You would need to re-install to make sure all subsequent steps were run. We should have a new release out sometime next week with fix.
