### ISSUE TITLE
Getting an Error 404 when Editing the Overide Panelizer

### ISSUE THREAD

**Issue by mudahayee** [drupalwxt/wxt-project#12]
I recently ran an update and not sure if anyone is having this issue, but I receive this error:
"We couldn't find that Web page
Error 404
We're sorry you ended up here. Sometimes a page gets moved or deleted."

When I select "Edit" for an "Overide" Panelize in the Basic Page content type.

Running Drupal core 8.7.11
Panelizer: 8.x-5.0-alpha3

Also have Layout Builder enabled (I have a feeling this might be causing the issue)

**Comment by sylus** [comment]
Hi there @mudahayee could you file this over at https://drupal.org/project/wxt? 

That is where we in general prefer issues our fault for not saying in README.md which I have a PR for. Though would u mind checking our latest release first to make sure is not still a problem?

https://github.com/drupalwxt/wxt/releases
