### ISSUE TITLE
Installation on Windows: ScriptHandler terminated with exception

### ISSUE THREAD

**Issue by juleskuehn** [drupalwxt/wxt-project#14]
Error during installation on Windows. Same as https://github.com/drupalwxt/wxt-project/issues/9
```
> DrupalWxT\WxT\ScriptHandler::deployLibraries
Script DrupalWxT\WxT\ScriptHandler::deployLibraries handling the post-update-cmd event terminated with an exception


  [ErrorException]
  proc_open(): CreateProcess failed, error code - 267
```
Is it possible to install in Windows?

**Comment by zachomedia** [comment]
@juleskuehn We don't see any logic that would prevent it from running on Windows, we will have to look further into it.

If you need something immediate, you can download at complete tar release from https://github.com/drupalwxt/wxt/releases/tag/3.0.6

**Comment by sylus** [comment]
Hi there @juleskuehn thanks for the issue.

If possible would you mind moving it over to https://drupal.org/project/wxt? as is our preferred.

Maybe some community member over there might be able to look at this but in general all of our developers to build on Linux. Though if you wanted to use Windows you can use WSL which I know works.

You can also just grab the already build tar so you don't have to run compsoer over at:

https://github.com/drupalwxt/wxt/releases

Thanks for the issue though and hopefully this helps :D

**Comment by juleskuehn** [comment]
Thanks for the suggestions. I did end up using the tar, but still having issues in Windows. I'll wait until I have a Linux server at my disposal to pursue it further.
