### ISSUE TITLE
Issues with D9 install

### ISSUE THREAD

**Issue by llangill** [drupalwxt/wxt-project#19]
Hey Guys,

I am trying to install WXT for a new site and when running through the install.php file, I am getting an error after the Database set up/during the Install site phaze. 

The website encountered an unexpected error. Please try again later.
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "path.alias_manager". in Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (line 1032 of /opt/bitnami/digitalcodeninja/digitalcodeninja.com/vendor/symfony/dependency-injection/ContainerBuilder.php).
Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (Line: 600)
Symfony\Component\DependencyInjection\ContainerBuilder->doGet() (Line: 558)
Symfony\Component\DependencyInjection\ContainerBuilder->get() (Line: 154)
Drupal\linkit\Plugin\Linkit\Matcher\EntityMatcher::create() (Line: 21)
Drupal\Core\Plugin\Factory\ContainerFactory->createInstance() (Line: 83)
Drupal\Component\Plugin\PluginManagerBase->createInstance() (Line: 81)
Drupal\Core\Plugin\DefaultLazyPluginCollection->initializePlugin() (Line: 80)
Drupal\Component\Plugin\LazyPluginCollection->get() (Line: 93)
Drupal\Core\Plugin\DefaultLazyPluginCollection->sort() (Line: 117)
Drupal\linkit\Entity\Profile->getMatchers() (Line: 154)
Drupal\linkit\Entity\Profile->getPluginCollections() (Line: 291)
Drupal\Core\Config\Entity\ConfigEntityBase->preSave() (Line: 494)
Drupal\Core\Entity\EntityStorageBase->doPreSave() (Line: 449)
Drupal\Core\Entity\EntityStorageBase->save() (Line: 263)
Drupal\Core\Config\Entity\ConfigEntityStorage->save() (Line: 339)
Drupal\Core\Entity\EntityBase->save() (Line: 591)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 384)
Drupal\Core\Config\ConfigInstaller->createConfiguration() (Line: 259)
Drupal\Core\Config\ConfigInstaller->installOptionalConfig() (Line: 84)
Drupal\Core\ProxyClass\Config\ConfigInstaller->installOptionalConfig() (Line: 1666)
install_install_profile() (Line: 699)
install_run_task() (Line: 574)
install_run_tasks() (Line: 118)
install_drupal() (Line: 44)

**Comment by sylus** [comment]
I just ran through this albeit through the drush installer and it worked fine.

```sh
composer create-project drupalwxt/wxt-project:9.x-dev site-example
```

```sh
drush si wxt --sites-subdir=default --db-url=mysql://root:root@db:3306/wxt --account-name=admin --account-pass=Drupal@2019 --site-mail=admin@example.com '--site-name=Drupal Install Profile (wxt)' wxt_extension_configure_form.select_all=TRUE 'install_configure_form.update_status_module=array(FALSE,FALSE)' --yes

 [success] Installation complete.

real    3m31.561s
user    1m48.751s
sys     0m16.323s
```

Maybe try again and also make sure you are running php 7.4.

If issue persists can file issue over at https://drupal.org/project/wxt
