### ISSUE TITLE
Update to latest D9 core (9.1.5).

### ISSUE THREAD

**Issue by liquidcms** [drupalwxt/wxt-project#20]
Not sure how this project has evolved in the 5 years or so since i last looked at it; but if i do a PR to update to newer version of core; is it likely to be merged?

Right now Wxt is at core 9.0.11 and core is at 9.1.5. I overrode wxt's dependencies with this:

        "drupal/core": "9.1.5 as 9.0.11",

in our local composer.json and the site seems to be functioning fine (not extensive tests for sure). Almost all the patches no longer apply.

Also, i see in the changelog you are at version 4.0.3 of Wxt; but that tag was never pushed.

**Comment by liquidcms** [comment]
moving to wxt queue

**Comment by olstjos** [comment]
this should go into https://www.drupal.org/project/issues/wxt
