### ISSUE TITLE
README for container set up is out of date.

### ISSUE THREAD

**Issue by liquidcms** [drupalwxt/wxt-project#21]
Guessing just README not keeping up with changes - but lots not working with the containers install guide in the README.

Trying to find the easiest install just to check if the flyout menu (Canada.ca theme option) works as the couple installs i have show numerous issues with it.

**Comment by liquidcms** [comment]
README here is also out of date: https://github.com/drupalwxt/docker-scaffold

**Comment by sylus** [comment]
Apologies I've centralized all of the docs in the docsite now which is linked in the main project README.

Should help!
