### ISSUE TITLE
CSS and JS files not being loaded correctly

### ISSUE THREAD

**Issue by gpatrick2** [drupalwxt/wxt-project#5]
The CSS and JS files for the theme are not being loaded by Drupal

Drupal is given the paths "/libraries/wet-boew/css" and "/libraries/wet-boew/js", while the correct path are
"/profiles/wxt/libraries/wet-boew/css" and "/profiles/wxt/libraries/wet-boew/js"

**Comment by sylus** [comment]
The correct paths in D8 are actually in the /libraries path so this is correct.

Can see our composer.json below:

https://github.com/drupalwxt/wxt/blob/8.x-2.x/composer.json#L204
