### ISSUE TITLE
Install error exception on deployLibraries

### ISSUE THREAD

**Issue by Joberrr** [drupalwxt/wxt-project#9]
Hi There,
Most of this install seems to work fine except I get the following error with when running composer create-project (Drupal 8.6.6) installing on XAMPP windows:

```
> DrupalWxT\WxT\ScriptHandler::deployLibraries
Script DrupalWxT\WxT\ScriptHandler::deployLibraries handling the post-update-cmd event terminated with an exception
[ErrorException]
proc_open(): CreateProcess failed, error code - 267
```

I'm guessing this is due to a missing or misnamed directory.

Is there a way for me to skip this part or fix the error?

Thanks,

Jobe

**Comment by Joberrr** [comment]
I gave up with XAMPP, but I've had complete success installing WxT using VirtualBox with Debian 9.5
thx

**Comment by juleskuehn** [comment]
Same problem. Does this work on Windows?
